name: bandgap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - pydantic=1.9.1
  - protobuf=3.19.1
  - jupyter=1.0.0
  - ipytest=0.12.0
  - rich=13.3.3
  # Dev
  - pytest
  - coverage
  - pytest-cov
  - pre-commit
  - black
  - pip
  - pip:
    - spyci
    