[project]
name = "bandgaps"
version = "0.1.0"
authors = [
   {name="Curtis Mayberry", email="Curtisma3@gmail.com"},
   {name="Yulin Deng"},
   {name="Thomas Pluck"},
]
readme = "README.md"
license = {file="LICENSE"}
description = "A set of open-source bandgap circuits"
keywords = ["hardware", "analog"]
requires-python = ">=3.10"
<<<<<<< HEAD
dependencies = [
    "viper-ic",
    "hdl21 == 5.0.0",
    "pytest == 8.2.0",
    "sky130-hdl21 == 5.0.0",
    "pandas == 2.2.2",
    "matplotlib == 3.8.4",
]

=======
>>>>>>> bd48b8d5228de005337b73c667cd5f9bad0abc4f
classifiers = [
    "Topic :: System :: Hardware",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

dependencies = [
    "viper-ic",
    "hdl21 == 5.0.0",
    "vlsir == 5.0.0",
    "pytest == 8.2.0",
    "sky130-hdl21 == 5.0.0",
]

[project.optional-dependencies]
dev = [
  "mkdocs-material == 9.5",
  "mkdocs-click == 0.8",
]

[project.urls]
"Home" = "https://github.com/cascode-labs/bandgaps"
"Documentation" = "https://github.com/cascode-labs/bandgaps"
"Source" = "https://github.com/cascode-labs/bandgaps"

[tool.viper.libraries.bandgap_sky130_v1]
path = "bandgap_sky130_v1"
process = "sky130A"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
