#!/usr/bin/env bash
# Runs as a postCreateCommand, once at the end of devcontainer creation
gh repo clone cascode-labs/viper workspaces/viper
uv venv .venv
source .venv/bin/activate
uv pip install -e ../viper
uv pip install -e .[dev]
